window.ID_CONTACT_ENDPOINT = 'https://core.idcontact.test.tweede.golf';
window.JWT_VERIFY_KEY = {
  "kty": "RSA",
  "n": "5_wRrT2T4GGvuQYcWjLr_lFe51sTV2FLd3GAaMiHN8Q_VT_XEhP_kZ6042l1Bj2VpZ2yMxv294JKwBCINc348VLYd-DfkMnJ4yX9LZHK2Wke6tCWBB9mYgGjMwCNdXczbl96x1_HevaTorvk91rzCvzw6vV08jtprAyN5aYMU4I0_cVJwi03bh_skraAB110mQSqi1QU_2z6Hkuf7-_x_bACxviWCyPCd_wkXNpFhTcRlfFeyKcy0pwFx1OLCDJ1qY7oU-z1wcypeOHeiUSxriSHlWaT24ke-J78GGVmnCZdu_MRuun5hvgaiWxnhIBmExJY6vRuMlwkbRqOft5QTQ",
  "e": "AQAB",
};
window.TRANSLATIONS = {
  nl: {
    title: 'ID Contact',
    slogan: 'Veilig contact met de gemeente',
    not_found: 'Pagina niet gevonden',
    provider_name: 'Gemeente Demodam',
    choose_auth_title: 'Inloggen',
    choose_comm_title: 'Hoe wil je contact?',
    start_title: 'Waar gaat je vraag over?',
    redirect: 'U wordt binnen enkele seconden doorverwezen...',
    // help page
    help_button: 'Hoe werkt het?',
    help_title: 'Hoe werkt ID Contact?',
    help_intro_bold: 'Bij persoonlijke vragen kunnen we je alleen helpen als we zeker weten dat jij het bent. Zo beschermen we jou en je gegevens.',
    help_intro_plain: 'Met ID Contact kun je veilig en digitaal contact hebben met de gemeente. Je hoeft dan minder vaak naar de balie.',
    help_explain_title: 'Zo werkt het',
    help_tab_call: 'Bellen',
    help_tab_chat: 'Chatten',
    help_tab_video: 'Videobellen',
    help_login_title: 'Inloggen',
    help_login_body: 'Inloggen kan met DigiD of andere veilige apps zoals IRMA.',
    help_login_extra: 'Download de app voor je verder gaat.',
    help_data_title: 'Doorgeven gegevens',
    help_data_body: 'Na het inloggen vraagt de app of die jouw gegevens mag doorgeven aan de gemeente.\nDe medewerker ziet alleen de gegevens die nodig zijn voor jouw vraag. Dat is meestal je naam en je burgerservicenummer (BSN).',
    help_data_dropdown_link: 'Wat gebeurt er met mijn gegevens?',
    help_data_dropdown_content: 'De medewerker ziet tijdens het contact de gegevens die je hebt doorgestuurd. Diegene weet dan dat jij het bent. Zo kunnen we jou het beste helpen.\nNa het gesprek worden de gegevens verwijderd.',
    help_chat_checkmark_title: 'Chatten',
    help_chat_checkmark_body: 'We verbinden jou met iemand van de gemeente.',
    help_chat_checkmark_body_bold: 'Je kunt nu veilig chatten.',
    help_video_checkmark_title: 'Videobellen',
    help_video_checkmark_body: 'De gemeentemedewerker weet nu dat jij het bent.',
    help_video_checkmark_body_bold: 'Je kunt dan veilig praten.',
    help_help_title: 'Hulp',
    help_question_title: 'Heb je een vraag over ID Contact?',
    help_other_title: 'Heb je een andere vraag?',
    help_more_title: 'Meer weten over ID Contact',
    help_more_body: 'Ga naar de pagina over ID Contact om meer te weten te komen.',
    help_more_link: 'meer over ID Contact',
    help_cta_call_title: 'Bel',
    help_cta_call_link: 'tel:012-3456789',
    help_cta_call_info: '(ma-vr 09.00-17.00)',
    help_cta_mail_title: 'Mail',
    help_cta_mail_link: 'mail:idcontact@demodam.nl',
    help_other_body: 'Voor persoonlijke vragen kun je het beste langskomen.',
    help_other_link: 'Maak hier een afspraak',
    help_other_extra: 'Je kunt ook bellen naar 0800-1234 of een mail sturen naar info@demodam.nl.', // TODO fix phone and e-mail
    //
    login_with: 'Inloggen met %auth_name%',
    confirm_auth_title: 'Je gaat zo door in de %auth_name% app',
    close_help: 'Terug naar de vorige pagina',
    back: 'terug',
    intro: 'Bij persoonlijke vragen moet je eerst inloggen. Zo weten we zeker dat jij het bent. En alleen dan kunnen we je helpen.',
    // reasons
    report_move: 'Veilig verhuizen',
    request_permit: 'Vergunning aanvragen',
    request_passport: 'Paspoort aanvragen',
  },
};
